---
name: Terraform

on:
  push:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: youtube

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
        role-session-name: YoutubeDemo

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.6"

    - name: Terraform Init
      run: terraform init
